### ISSUE TITLE
Buggy behavior of extractors(warping)

### ISSUE THREAD

**Issue by BalaM314** [BalaM314/Untitled-Electron-Game#4]
Extractors currently warp items to their middle when picked up. Due to the mechanics of the extractor this cannot be abused to create something faster than a belt chain, but it's still weird.

**Comment by RickAstly** [comment]
![image](https://user-images.githubusercontent.com/89779977/149650485-eb698e07-ff72-4814-8fdd-6ffb313d07ee.png)
@BalaM314 u dum ofc you can abuse it
fix shd be ez

**Comment by BalaM314** [comment]
well you _could_ only pull items from belts when the item is in or near the middle, but then if the belt backstuffs extractors will never work
I think this shall forever be left as a quirk of alpha

**Comment by RickAstly** [comment]
just have it only pull items from belts if the item has moved more than halfway
that way if the belt stalls, the extractor will still pull items
also, make sure to set the position perpendicular to the direction of the extractor but not the other way
that way sideways extractors will warp (unavoidable) but forward extractors won't
