### ISSUE TITLE
Waugh

### ISSUE THREAD

**Issue by Robotsrule4545** [BalaM314/Untitled-Electron-Game#9]
<img width="413" alt="Screenshot 2022-12-06 at 12 35 19 PM" src="https://user-images.githubusercontent.com/77372650/205816057-997e834d-56e4-4e1a-b81c-073e464e3b09.png">

maybe the div needs to be

*T H I C K E R*

**Comment by BalaM314** [comment]
Only took 2 years!
@Robotsrule4545 If you're interested, the game has come a long way since you last played.
